name: visualbeast
favicon: null
layout_spectrum: 0.08945184899494052
typography_spectrum: 0.8447308435570449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#13100b'
    - '#75190a'
    - '#d2c4a7'
    - '#b48a4e'
  brandStrength: 0.44452400389127433
  lightness: 0.9107434579636902
  saturation: 0.6938913469202816
  rhythmicContrast: 0.8740241292398423
purpose: []
